exports.constants = {
  INPUTS_REQUIRED: "All inputs required",
  DRAFT_CREATED: "Draft Created",
  DRAFT_ERROR: "Some error occurred while creating the draft post",
  POST_NOT_FOUND: "post not found with given id",
  POST_UPDATED: "post updated",
  POST_PUBLISHED: "post published",
  POST_DELETED: "post deleted",
  TOKEN_TYPE: "x-access-token",
  TOKEN_REQUIRED: "A token is required for authentication",
  INVALID_TOKEN: "Invalid Token",
  USER_EXISTS: "User Already Exist",
  SIGNED_UP: "Signed Up Succesfully",
  INVALID_CREDENTIALS: "Invalid Credentials",
  USER_NOT_FOUND: "User does not exists",
  RUNNING_PORT: "Server is runnig on the port ",
  CONNECTED: "Connected to the database",
  NOT_CONNECTED: "couldn't conected to the database ",
};
